# Site settings
title: AYO ' FLOWER FRUIT WATER
description: |
  AYO Flower fruit water is coming soon!
owner: AYO water Lty Ptd # or company name
first_published: CopyRight # if migrating another site, the year of your first publish
email: service@ayowater.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.ayowater.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/AYO_WATER
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/AYOWATER/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:service@ayowater.com
  #flickr:
  instagram: https://www.instagram.com/ayo_water/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  weibo: http://weibo.com/
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  weixin: contact
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
